#application:
#  db1:
#    datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/db1
#      username: myDb
#      password: myDb
#      hikari:
#        connection-timeout: 30000
#        idle-timeout: 60000
#        max-lifetime: 1800000
#        maximum-pool-size: 20
#        pool-name: PoolDb1
#    jpa:
#      show-sql: true
#      generate-ddl: true
#      open-in-view: true
#
#  db2:
#    datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3307/db2
#      username: myDb
#      password: myDb
#      hikari:
#        connection-timeout: 30000
#        idle-timeout: 60000
#        max-lifetime: 1800000
#        maximum-pool-size: 20
#        pool-name: PoolDb2
#    jpa:
#      show-sql: true
#      generate-ddl: true
#      open-in-view: true
#
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop

